# Generated by Django 5.0.2 on 2024-05-07 15:32

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forests',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=32737)),
            ],
            options={
                'verbose_name_plural': 'forests',
                'db_table': 'forests',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Hospitals',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('keph_level', models.CharField(blank=True, max_length=100, null=True)),
                ('facility_type', models.CharField(blank=True, max_length=100, null=True)),
                ('facility_category', models.CharField(blank=True, max_length=100, null=True)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=32737)),
            ],
            options={
                'verbose_name_plural': 'hospitals',
                'db_table': 'hospitals',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Rivers',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('layer', models.CharField(blank=True, max_length=17, null=True)),
                ('dgc_codice', models.FloatField(blank=True, null=True)),
                ('type', models.CharField(blank=True, max_length=30, null=True)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
                ('code', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(blank=True, null=True, srid=32737)),
            ],
            options={
                'verbose_name_plural': 'rivers',
                'db_table': 'rivers',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Roads',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('layer', models.CharField(blank=True, max_length=20, null=True)),
                ('old_rid', models.CharField(blank=True, max_length=40, null=True)),
                ('length', models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True)),
                ('roadclass', models.CharField(blank=True, max_length=5, null=True)),
                ('roadnum', models.CharField(blank=True, max_length=20, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(blank=True, null=True, srid=32737)),
            ],
            options={
                'verbose_name_plural': 'roads',
                'db_table': 'roads',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Schools',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('school_name', models.CharField(blank=True, max_length=100, null=True)),
                ('level', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('zone', models.CharField(blank=True, max_length=100, null=True)),
                ('ward', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('sub_county', models.CharField(blank=True, max_length=100, null=True)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=32737)),
            ],
            options={
                'verbose_name_plural': 'schools',
                'db_table': 'schools',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Subcounty',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('gm_type', models.CharField(blank=True, max_length=17, null=True)),
                ('const_no', models.IntegerField(blank=True, null=True)),
                ('const_nam', models.CharField(blank=True, max_length=9, null=True)),
                ('county_nam', models.CharField(blank=True, max_length=4, null=True)),
                ('subcounty', models.CharField(blank=True, max_length=50, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=32737)),
            ],
            options={
                'verbose_name_plural': 'subcounties',
                'db_table': 'subcounty',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Towns',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('layer', models.CharField(blank=True, max_length=21, null=True)),
                ('tname', models.CharField(blank=True, max_length=30, null=True)),
                ('admstatus', models.CharField(blank=True, max_length=20, null=True)),
                ('type', models.CharField(blank=True, max_length=20, null=True)),
                ('dont_label', models.CharField(blank=True, max_length=5, null=True)),
                ('source', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('labels', models.CharField(blank=True, max_length=30, null=True)),
                ('new_status', models.CharField(blank=True, max_length=25, null=True)),
                ('origstatus', models.CharField(blank=True, max_length=20, null=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=32737)),
            ],
            options={
                'verbose_name_plural': 'towns',
                'db_table': 'towns',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Wards',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=40, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=32737)),
            ],
            options={
                'verbose_name_plural': 'wards',
                'db_table': 'wards',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='WaterBodies',
            fields=[
                ('gid', models.AutoField(primary_key=True, serialize=False)),
                ('layer', models.CharField(blank=True, max_length=20, null=True)),
                ('id', models.FloatField(blank=True, null=True)),
                ('osm_id', models.CharField(blank=True, max_length=20, null=True)),
                ('z_order', models.FloatField(blank=True, null=True)),
                ('natural', models.CharField(blank=True, max_length=80, null=True)),
                ('name', models.CharField(blank=True, max_length=80, null=True)),
                ('name_en', models.CharField(blank=True, max_length=80, null=True)),
                ('type', models.CharField(blank=True, max_length=80, null=True)),
                ('ele', models.CharField(blank=True, max_length=80, null=True)),
                ('water', models.CharField(blank=True, max_length=80, null=True)),
                ('wetland', models.CharField(blank=True, max_length=80, null=True)),
                ('wood', models.CharField(blank=True, max_length=80, null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=32737)),
            ],
            options={
                'verbose_name_plural': 'water_bodies',
                'db_table': 'water_bodies',
                'managed': True,
            },
        ),
    ]
