# Generated by Django 5.0.2 on 2024-06-06 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0001_initial"),
    ]

    operations = []
